### ISSUE TITLE
Stage 1 alloc error tracking issue (error code 20910)

### ISSUE THREAD

**Issue by mkwcat** [WiiLink24/wfc-patcher-wii#26]
Reported error code 20910 on login

- [x] Mario Sports Mix
- [ ] Samba de Amigo
- [x] UNO WiiWare
- [ ] Pokemon Mystery Dungeon Adventure Squad WiiWare titles (WPAJ, WPFJ, WPHJ)
- [ ] Guitar Hero Metallica
- [ ] 007 - Quantum of Solace (RJ2)
- [ ] NHL 2K10
- [ ] NHL 2K11
- [ ] Fortune Street (only some cases; the code incorrectly relies on a relocatable module)
